version: "3.8"

services:
  backend:
    build: ./todo-backend
    ports:
      - "3000:3000"
    volumes:
      - ./todo-backend:/app
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/todos
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build: ./todo-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./todo-frontend:/app
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
